In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split 
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('../Dataset/GR2CLEAN.csv')
df.head()

,index,Date,Open,High,Low,Close,Volume,Time,Prev_High,Prev_Low,Prev_Volume,Prev_Open,Prev_Close,CloseChange,HighChange,Prev_CO_Diff,Prev_HL_Diff,isUp
0,1,2014-01-03,18.97,19.60,18.97,19.32,56629,1,20.19,18.90,67963.0,19.87,19.12,0.20,-0.59,-0.75,1.29,True
1,2,2014-01-06,19.30,19.73,19.10,19.44,59479,2,19.60,18.97,56629.0,18.97,19.32,0.12,0.13,0.35,0.63,True
2,3,2014-01-07,19.50,19.72,19.30,19.48,44238,3,19.73,19.10,59479.0,19.30,19.44,0.04,-0.01,0.14,0.63,True
3,4,2014-01-08,19.50,20.38,19.45,19.86,148330,4,19.72,19.30,44238.0,19.50,19.48,0.38,0.66,-0.02,0.42,True
4,5,2014-01-09,19.76,20.49,19.31,19.45,75597,5,20.38,19.45,148330.0,19.50,19.86,-0.41,0.11,0.36,0.93,False

In [3]:

df.head()

,index,Date,Open,High,Low,Close,Volume,Time,Prev_High,Prev_Low,Prev_Volume,Prev_Open,Prev_Close,CloseChange,HighChange,Prev_CO_Diff,Prev_HL_Diff,isUp
0,1,2014-01-03,18.97,19.60,18.97,19.32,56629,1,20.19,18.90,67963.0,19.87,19.12,0.20,-0.59,-0.75,1.29,True
1,2,2014-01-06,19.30,19.73,19.10,19.44,59479,2,19.60,18.97,56629.0,18.97,19.32,0.12,0.13,0.35,0.63,True
2,3,2014-01-07,19.50,19.72,19.30,19.48,44238,3,19.73,19.10,59479.0,19.30,19.44,0.04,-0.01,0.14,0.63,True
3,4,2014-01-08,19.50,20.38,19.45,19.86,148330,4,19.72,19.30,44238.0,19.50,19.48,0.38,0.66,-0.02,0.42,True
4,5,2014-01-09,19.76,20.49,19.31,19.45,75597,5,20.38,19.45,148330.0,19.50,19.86,-0.41,0.11,0.36,0.93,False

In [4]:
X = df[['Time','Prev_High',"Prev_Low",'Prev_Open','Prev_Close','Prev_CO_Diff','Prev_HL_Diff']]

# in df replace True with 1 and False with -1
y = df['Close'] 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
neighbours = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,18,19,20]
r2 = []
best_neighbour = None
knn = KNeighborsRegressor(n_neighbors=6)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
r2_score(y_test, y_pred)

0.997397759863879

False